// Translate source-owned UI fragments before interpolating user data.
// Names, paths, passwords, commands and protocol values are never translated.
const NexusI18n = (() => {
  const english = {
  "Installer votre NAS": "Set up your NAS",
  "Bienvenue sur Nexus": "Welcome to Nexus",
  "Entrez le code affiché à la fin de l’installation, puis créez votre compte administrateur.": "Enter the code shown after installation, then create your administrator account.",
  "Connectez-vous avec votre compte Nexus.": "Sign in with your Nexus account.",
  "Code d’installation": "Installation code",
  "Nom d’utilisateur": "Username",
  "Mot de passe": "Password",
  "Nom du serveur": "Server name",
  "Créer mon serveur": "Create my server",
  "Se connecter": "Sign in",
  "Administrateur": "Administrator",
  "Utilisateur": "User",
  "CONNECTÉ": "CONNECTED",
  "Le service Linux n’a pas retourné la liste des volumes": "The Linux service did not return the volume list",
  "Compte connecté": "Signed in",
  "Votre compte est enregistré. Le serveur ne peut pas encore charger la configuration.": "Your account is saved. The server cannot load its configuration yet.",
  "Réessayer": "Try again",
  "Déconnexion": "Sign out",
  "Si le problème persiste, consultez les journaux du service Nexus et de Nexus Agent.": "If the problem persists, check the Nexus and Nexus Agent service logs.",
  "Mesures système indisponibles : ": "System metrics unavailable: ",
  "Stockage": "Storage",
  "Partages réseau": "Network shares",
  "La configuration des partages ne peut pas être chargée.": "The share configuration could not be loaded.",
  "Utilisateurs": "Users",
  "Fichiers": "Files",
  "Connexion interrompue : ": "Connection interrupted: ",
  "Connexion interrompue": "Connection interrupted",
  "Service temporairement indisponible": "Service temporarily unavailable",
  "PROCESSEUR": "PROCESSOR",
  "MÉMOIRE VIVE": "MEMORY",
  "Historique réel de ": "Recorded history of ",
  "Maintenant": "Now",
  "En attente de la première mesure…": "Waiting for the first sample…",
  "Première mesure reçue. La courbe se construit toutes les 10 secondes.": "First sample received. The chart updates every 10 seconds.",
  " mesures réelles · actualisation toutes les 10 secondes": " recorded samples · updated every 10 seconds",
  "Les mesures sont temporairement indisponibles.": "Metrics are temporarily unavailable.",
  "Service Linux": "Linux service",
  "VOTRE ESPACE, EN TOUTE SÉRÉNITÉ": "YOUR SPACE, YOUR PEACE OF MIND",
  "Bonjour, ": "Hello, ",
  "Vos données à portée de main. Votre serveur sous contrôle.": "Your data within reach. Your server under control.",
  "Connecté au NAS": "Connected to NAS",
  "Processeur": "Processor",
  "Charge actuelle": "Current load",
  "Mémoire utilisée": "Memory in use",
  "Mémoire": "Memory",
  "Partages": "Shares",
  "Vos espaces accessibles": "Your accessible spaces",
  "Durée de fonctionnement": "Uptime",
  "Depuis le dernier démarrage": "Since the last boot",
  "Le rythme de votre serveur": "Your server at a glance",
  "Les dix dernières minutes, mesurées en direct.": "The last ten minutes, measured live.",
  "Une mesure / 10 s": "One sample / 10 s",
  "Activité du processeur": "Processor activity",
  "Une vue précise de la charge du serveur.": "A clear view of your server load.",
  "Utilisation de la mémoire": "Memory usage",
  "Gardez un œil sur les ressources disponibles.": "Keep an eye on available resources.",
  "Un serveur, tous vos appareils": "One server, all your devices",
  "Retrouvez vos données où vous en avez besoin.": "Access your data wherever you need it.",
  "De la place pour l’essentiel": "Room for what matters",
  "Votre espace de stockage actuel.": "Your current storage space.",
  "ESPACE DISPONIBLE": "AVAILABLE SPACE",
  "utilisé": "used",
  "Utilisé": "Used",
  "Disponible": "Available",
  "Actualiser": "Refresh",
  "Nexus · votre cloud personnel": "Nexus · your personal cloud",
  "sur ": "of ",
  " de capacité": " total capacity",
  "Volume indisponible": "Volume unavailable",
  "Depuis votre navigateur": "Web browser",
  "Explorateur Windows": "Windows Explorer",
  "Compte SMB": "SMB account",
  "Adresse copiée": "Copied to clipboard",
  "Mise à jour": "Update",
  "Terminé": "Completed",
  "En cours": "In progress",
  "Échec": "Failed",
  "Préparation du disque": "Disk preparation",
  "La vie de votre NAS": "Your NAS activity",
  "Vos dernières opérations, en un coup d’œil.": "Your latest operations at a glance.",
  "Tout est calme. Vos prochaines opérations apparaîtront ici.": "All is quiet. Your next operations will appear here.",
  "Les volumes sont indisponibles. Réessayez lorsque le service Linux est prêt.": "Volumes are unavailable. Try again when the Linux service is ready.",
  "CONFIGURATION · STOCKAGE ET ACCÈS": "SETUP · STORAGE AND ACCESS",
  "Votre premier partage": "Your first share",
  "Vous pouvez conserver les disques actuels ou préparer un disque vide. Les fichiers seront accessibles dans le navigateur et par SMB.": "Keep your current disks or prepare an unused disk. Files will be accessible in your browser and over SMB.",
  "Préparer un disque…": "Prepare a disk…",
  "Créer le partage et terminer": "Create share and finish",
  "Terminer sans partage": "Finish without a share",
  "Nom du partage": "Share name",
  "Volumes disponibles": "Available volumes",
  "Partitionnez un disque inutilisé en volumes ext4, montés automatiquement au démarrage.": "Partition an unused disk into ext4 volumes that mount automatically at boot.",
  "DISQUE": "DISK",
  "CAPACITÉ": "CAPACITY",
  "ÉTAT": "STATUS",
  "ACTION": "ACTION",
  "ACTIONS": "ACTIONS",
  "Partitionner…": "Partition…",
  "Aucun disque détecté.": "No disks detected.",
  "Le partitionnement efface le disque entier. Les disques montés, système, swap, RAID, LVM et chiffrés sont protégés.": "Partitioning erases the entire disk. Mounted, system, swap, RAID, LVM and encrypted disks are protected.",
  "Disponible pour partitionnement": "Available for partitioning",
  "Fermer": "Close",
  "Annuler": "Cancel",
  "Continuer": "Continue",
  "Votre saisie": "Your input",
  "Confirmer l’action": "Confirm action",
  "Confirmer": "Confirm",
  "Préparer un disque": "Prepare a disk",
  "Aucun disque disponible pour le partitionnement": "No disks available for partitioning",
  "Le disque système et les disques actuellement utilisés sont protégés. Vous pouvez continuer avec le stockage système ou ajouter un disque inutilisé au serveur.": "The system disk and disks currently in use are protected. Continue with system storage or add an unused disk to the server.",
  "Disque indisponible": "Disk unavailable",
  "Cette opération détruit toutes les partitions et tous les fichiers du disque choisi.": "This operation destroys all partitions and files on the selected disk.",
  "Disque": "Disk",
  "Partitions (une par ligne : label, taille en Gio ; * pour l’espace restant)": "Partitions (one per line: label, size in GiB; * for remaining space)",
  "Préparer le plan": "Prepare plan",
  "Confirmer l’effacement de ": "Confirm erasing ",
  "Saisissez exactement : ": "Type exactly: ",
  "Effacer et créer les volumes": "Erase and create volumes",
  "espace restant": "remaining space",
  "Préparation en cours": "Preparation in progress",
  "Le serveur prépare votre disque. Ne débranchez pas le disque.": "The server is preparing your disk. Do not disconnect it.",
  "Opération introuvable": "Operation not found",
  "Créer un partage": "Create a share",
  "Les dossiers accessibles depuis le navigateur et vos appareils SMB.": "Folders accessible in your browser and from your SMB devices.",
  "NOM": "NAME",
  "DOSSIER": "FOLDER",
  "ACCÈS": "ACCESS",
  "Modifier": "Edit",
  "Retirer": "Remove",
  "Créez votre premier partage.": "Create your first share.",
  "lecture / écriture": "read / write",
  "lecture seule": "read only",
  "lecture": "read",
  "Retirer cet accès réseau ? Les fichiers seront conservés sur le disque.": "Remove this network share? Files will remain on the disk.",
  "Créer": "Create",
  " un partage": " a share",
  "Nom": "Name",
  "Utilisateurs autorisés": "Allowed users",
  "Lecture / écriture": "Read / write",
  "Lecture seule": "Read only",
  "Enregistrer": "Save",
  "Ajouter un utilisateur": "Add a user",
  "Comptes Nexus et SMB. Les connexions SSH ne sont pas autorisées pour ces comptes.": "Nexus and SMB accounts. SSH sign-ins are not allowed for these accounts.",
  "COMPTE": "ACCOUNT",
  "RÔLE": "ROLE",
  "Actif": "Active",
  "Désactivé": "Disabled",
  "Désactiver": "Disable",
  "Ajouter un compte": "Add an account",
  "Rôle": "Role",
  "Créer le compte": "Create account",
  "Désactiver les accès web et SMB de ": "Disable web and SMB access for ",
  "Compte ": "Account ",
  "Nouveau mot de passe (facultatif)": "New password (optional)",
  "État": "Status",
  "Un espace pour vos documents, vos photos et tout ce qui compte.": "A space for your documents, photos and everything that matters.",
  "Votre espace": "Your space",
  "Dossier parent": "Parent folder",
  "Nouveau dossier": "New folder",
  "Déposer des fichiers": "Upload files",
  "Choisir des fichiers à déposer": "Choose files to upload",
  "Faites de la place à vos fichiers.": "Make room for your files.",
  "Glissez-les ici, ou cliquez pour les déposer. Ils restent chez vous.": "Drop them here, or click to upload. They stay with you.",
  "Votre cloud privé": "Your private cloud",
  "Chemin du dossier": "Folder path",
  "Rechercher un fichier…": "Search files…",
  "Rechercher dans ce dossier": "Search this folder",
  "TAILLE": "SIZE",
  "DERNIÈRE MODIFICATION": "LAST MODIFIED",
  "Nom du nouveau dossier": "New folder name",
  "Corbeille": "Trash",
  "Les fichiers retirés occupent encore de l’espace jusqu’à ce que la corbeille soit vidée.": "Removed files still take up space until the trash is emptied.",
  "La corbeille est vide.": "The trash is empty.",
  "Vider définitivement…": "Empty permanently…",
  "Restaurer": "Restore",
  "Tapez VIDER LA CORBEILLE. Cette suppression est définitive.": "Type EMPTY TRASH. This deletion is permanent.",
  "Aucun partage autorisé.": "No accessible shares.",
  " éléments": " items",
  " élément": " item",
  "Dossier": "Folder",
  "Fichier": "File",
  "Ouvrir": "Open",
  "Télécharger": "Download",
  "Renommer": "Rename",
  "Nouveau nom": "New name",
  "Aucun résultat pour cette recherche": "No matching results",
  "Votre prochain fichier commence ici": "Your next file starts here",
  "Essayez avec un autre nom.": "Try another name.",
  "Déposez votre premier fichier pour remplir cet espace.": "Upload your first file to fill this space.",
  "Déplacer « ": "Move “",
  " » dans la corbeille ?": "” to the trash?",
  "Partage en lecture seule": "Read-only share",
  "envoi…": "uploading…",
  "Transfert interrompu": "Transfer interrupted",
  "Transfert terminé.": "Transfer complete.",
  "Paramètres": "Settings",
  "Identité du serveur, accès et mises à jour.": "Server identity, access and updates.",
  "Accès réseau local": "Local network access",
  "Nom SMB": "SMB username",
  "Utilisez HTTPS ou un tunnel SSH sur un réseau non fiable.": "Use HTTPS or an SSH tunnel on an untrusted network.",
  "Mises à jour GitHub": "GitHub updates",
  "Publications stables de Nariod68/Nexus-nas": "Stable releases from Nariod68/Nexus-nas",
  "Rechercher": "Check",
  "Installer la nouvelle version": "Install new version",
  "Revenir à la version précédente": "Roll back to previous version",
  "Serveur": "Server",
  "Redémarrer le serveur…": "Restart server…",
  "Nom enregistré": "Name saved",
  "Nouvelle version : ": "New version: ",
  "Vous êtes à jour (": "You are up to date (",
  "Installer la dernière version ? L’interface sera temporairement indisponible.": "Install the latest version? The interface will be temporarily unavailable.",
  "Restaurer la version précédente ?": "Restore the previous version?",
  "Mise à jour lancée. Attendez puis reconnectez-vous. Le suivi figure sur la vue d’ensemble.": "Update started. Wait, then sign in again. Track progress on the overview page.",
  "Tapez REDÉMARRER pour confirmer": "Type RESTART to confirm",
  "Redémarrage dans quelques secondes.": "Restarting in a few seconds.",
  "Mon compte": "My account",
  "Changer mon mot de passe": "Change my password",
  "Mot de passe actuel": "Current password",
  "Nouveau mot de passe Nexus et SMB": "New Nexus and SMB password",
  "Enregistrer et me reconnecter": "Save and sign in again",
  "Créez vos comptes, puis vos partages. La rubrique Fichiers permet les transferts. Le compte SMB porte le préfixe nx_.": "Create accounts, then shares. Use Files for transfers. SMB usernames start with nx_.",
  "Service Nexus indisponible": "Nexus service unavailable",
  "Lancez le service Nexus pour utiliser cette interface.": "Start the Nexus service to use this interface.",
  "Connecter un lecteur réseau": "Connect a network drive",
  "Connecter": "Connect",
  "Ce partage est accessible depuis un autre ordinateur du même réseau.": "This share is accessible from another computer on the same network.",
  "Chemin Windows": "Windows path",
  "Copier le chemin": "Copy path",
  "Utilisez le même mot de passe que votre compte Nexus.": "Use the same password as your Nexus account.",
  "Dans l’Explorateur Windows, ouvrez Ce PC puis Connecter un lecteur réseau.": "In Windows Explorer, open This PC, then Map network drive.",
  "Collez le chemin et cochez Se connecter à l’aide d’informations d’identification différentes.": "Paste the path and check Connect using different credentials.",
  "Saisissez votre compte SMB et votre mot de passe Nexus.": "Enter your SMB username and Nexus password.",
  "Lettre du lecteur": "Drive letter",
  "Commande Windows": "Windows command",
  "Copier la commande": "Copy command",
  "Télécharger l’assistant Windows": "Download Windows helper",
  "Ouvrez le fichier .cmd sur Windows : il demande votre mot de passe et connecte le lecteur. Aucun mot de passe n’est inclus dans le fichier. Choisissez une lettre libre.": "Open the .cmd file on Windows: it asks for your password and maps the drive. The file contains no password. Choose an unused drive letter.",
  "Linux et macOS": "Linux and macOS",
  "La connexion ne fonctionne pas ?": "Connection not working?",
  "Vérifiez que votre compte est autorisé dans Partages réseau et que le port TCP 445 du serveur est accessible. Windows peut avoir mémorisé un autre compte : retirez uniquement les anciens identifiants de ce NAS dans le Gestionnaire d’identification.": "Check your account is allowed in Network shares and the server TCP port 445 is reachable. Windows may have saved another account: remove only this NAS’s old credentials in Credential Manager.",
  "Dans PowerShell : ": "In PowerShell: ",
  ". La commande de connexion affiche le numéro d’erreur précis.": ". The connection command shows the exact error number.",
  "Adresse réseau indisponible": "Network address unavailable",
  "Navigation principale": "Main navigation",
  "Nexus, accueil": "Nexus, home",
  "serveur personnel": "personal server",
  "ESPACE NAS": "NAS SPACE",
  "SYSTÈME": "SYSTEM",
  "Vue d’ensemble": "Overview",
  "Mon serveur": "My server",
  "Aide": "Help",
  "Connexion au service Nexus…": "Connecting to Nexus…",
  "Compte de démonstration": "Account",
  "Nexus — Tableau de bord": "Nexus — Dashboard",
  "Stockage système (sans formatage)": "System storage (no formatting)",
  "Stockage système": "System storage",
  "Chemin refusé": "Path denied",
  "Dossier ou lien refusé": "Directory or symlink denied",
  "Confirmation incorrecte": "Incorrect confirmation",
  "Identifiants incorrects": "Invalid credentials",
  "Accès refusé": "Access denied",
  "Disque utilisé : une partition est montée": "Disk in use: a partition is mounted",
  "Impossible de vérifier l’utilisation de ce disque dans le noyau": "Unable to verify disk usage in the kernel",
  "Disque système protégé": "Protected system disk",
  "Toutes les données seront détruites.": "All data will be destroyed.",
  "Session expirée": "Session expired",
  "Partage introuvable": "Share not found",
  "Confirmation requise": "Confirmation required",
  "Fichier trop volumineux ou espace insuffisant": "File too large or insufficient space",
  "Le mot de passe doit contenir entre 12 et 256 caractères": "The password must contain between 12 and 256 characters",
  "Nom : 3 à 20 lettres minuscules, chiffres, tirets ou underscores": "Name: 3 to 20 lowercase letters, digits, hyphens or underscores",
  "Le partage est retiré. Ses fichiers sont conservés.": "The share was removed. Its files are preserved.",
  "Sélectionner au moins un utilisateur": "Select at least one user",
  "Utilisateur SMB inconnu ou en double": "Unknown or duplicate SMB user",
  "Volume indisponible ou non monté": "Volume unavailable or not mounted",
  "Retirer ce partage avant de changer son volume": "Remove this share before changing its volume",
  "Volume symbolique refusé": "Symlink volume denied",
  "Dossier refusé": "Directory denied",
  "Mot de passe SMB invalide (12 caractères minimum, sans retour à la ligne)": "Invalid SMB password (at least 12 characters, no line breaks)",
  "Ce compte Linux existe déjà hors de Nexus": "This Linux account already exists outside Nexus",
  "Une mise à jour est en cours": "An update is in progress",
  "Une opération système est déjà en cours": "A system operation is already in progress",
  "Préparation": "Preparing",
  "Démarrage": "Starting",
  "Détection des disques indisponible : ": "Disk detection unavailable: ",
  "Compte Nexus inconnu": "Unknown Nexus account",
  "Nom de serveur invalide": "Invalid server name",
  "Attendre la fin de l’opération disque avant de mettre à jour": "Wait for the disk operation to finish before updating",
  "Action système non autorisée": "System action not allowed",
  "Requête refusée": "Request denied",
  "Requête trop volumineuse": "Request too large",
  "Numéro de version invalide": "Invalid version number",
  "Aucune publication GitHub disponible": "No GitHub release available",
  "Le tag de publication doit commencer par v": "The release tag must start with v",
  "Publication non stable": "Not a stable release",
  "Racine symbolique refusée": "Symlink root denied",
  "La racine est protégée": "The root folder is protected",
  "Fichier ou lien refusé": "File or symlink denied",
  "Objet refusé": "Item denied",
  "Identifiant de corbeille refusé": "Invalid trash identifier",
  "Lien refusé": "Symlink denied",
  "Seuls les fichiers ordinaires peuvent être renommés": "Only regular files and folders can be renamed",
  "Identité de périphérique invalide": "Invalid device identity",
  "Prévoir entre 1 et 16 partitions": "Provide between 1 and 16 partitions",
  "Label ext4 : 1 à 16 lettres, chiffres ou tirets": "ext4 label: 1 to 16 letters, digits or hyphens",
  "Taille entière en Gio, ou espace restant pour la dernière partition": "Whole-number size in GiB, or remaining space for the last partition",
  "Les partitions dépassent la capacité disponible": "Partitions exceed available capacity",
  "Périphérique bloc refusé": "Block device denied",
  "Disque non détecté": "Disk not detected",
  "Trop de plans en attente": "Too many pending plans",
  "Toutes les données et partitions de ce disque seront détruites. Cette opération est irréversible.": "All data and partitions on this disk will be destroyed. This operation is irreversible.",
  "Plan expiré ou confirmation incorrecte": "Plan expired or incorrect confirmation",
  "Le disque a changé depuis la préparation": "The disk changed since the plan was prepared",
  "Les nouvelles partitions ne sont pas disponibles": "The new partitions are unavailable",
  "Partition inattendue": "Unexpected partition",
  "UUID de volume invalide": "Invalid volume UUID",
  "Ce périphérique n’est pas un disque entier": "This device is not a whole disk",
  "Disque virtuel réservé aux tests": "Virtual disk reserved for tests",
  "Disque en lecture seule": "Read-only disk",
  "Disque utilisé pour le swap": "Disk used for swap",
  "Disque membre d’un RAID, LVM ou volume chiffré": "Disk belongs to RAID, LVM or an encrypted volume",
  "Disque utilisé par un autre périphérique": "Disk used by another device",
  "Origine refusée": "Origin denied",
  "Code d’installation incorrect": "Incorrect installation code",
  "Le serveur est déjà configuré": "The server is already configured",
  "Connexion requise": "Sign-in required",
  "Réservé à un administrateur": "Administrator access required",
  "Mot de passe actuel incorrect": "Incorrect current password",
  "Rôle invalide": "Invalid role",
  "Ce compte existe déjà": "This account already exists",
  "Vous ne pouvez pas désactiver votre propre compte": "You cannot disable your own account",
  "Compte inconnu": "Unknown account",
  "Vous ne pouvez pas retirer vos propres droits administrateur": "You cannot remove your own administrator rights",
  "Un nouveau mot de passe est requis pour réactiver le compte": "A new password is required to reactivate the account",
  "Accès au partage refusé": "Share access denied",
  "Volume déconnecté : accès aux fichiers suspendu": "Volume disconnected: file access suspended",
  "Déplacé dans la corbeille du partage": "Moved to the share trash",
  "Route inconnue": "Unknown route",
  "Méthode refusée": "Method denied",
  "Fichier introuvable": "File not found",
  "Trop de tentatives. Réessayez dans 15 minutes.": "Too many attempts. Try again in 15 minutes.",
  "JSON invalide": "Invalid JSON",
  "Vérification de la publication": "Checking release",
  "Redémarrage sur la nouvelle version": "Restarting on the new version",
  "La nouvelle version ne répond pas": "The new version is not responding",
  "Version précédente restaurée.": "Previous version restored.",
  "Nexus est à jour": "Nexus is up to date",
  "Paquet Nexus ou somme SHA-256 absent de la publication": "Nexus bundle or SHA-256 checksum missing from release",
  "Somme SHA-256 invalide": "Invalid SHA-256 checksum",
  "Empreinte GitHub incohérente": "GitHub checksum mismatch",
  " installé": " installed",
  "La lecture des interfaces réseau est indisponible. Les fonctions du NAS restent accessibles à l’adresse utilisée dans votre navigateur.": "Network interface information is unavailable. NAS features remain accessible at the address used in your browser.",
  "Opération interrompue par le redémarrage de l’agent. Vérifier le disque avant de réessayer.": "Operation interrupted by the agent restarting. Check the disk before trying again.",
  "Gio": "GiB",
  "Tio": "TiB",
  "Votre espace vous attend": "Your space is waiting",
  "Créez un partage ou demandez un accès à votre administrateur.": "Create a share or ask your administrator for access.",
  "Copier": "Copy",
  "Langue": "Language",
  "Langue / Language": "Language / Langue",
  "Ce compte n’est pas autorisé pour ce partage SMB. Ajoutez-le dans les utilisateurs autorisés du partage avant de connecter le lecteur.": "This account is not allowed on this SMB share. Add it to the share’s allowed users before mapping the drive.",
  "Mot de passe Nexus": "Nexus password",
  "Entrez votre mot de passe Nexus, puis cliquez sur Connecter.": "Enter your Nexus password, then click Connect.",
  "Saisissez votre mot de passe Nexus.": "Enter your Nexus password.",
  "Aucune lettre de lecteur disponible.": "No drive letters available.",
  "Vérification de la connexion…": "Checking connection…",
  "Le NAS ne répond pas sur le port de partage. Vérifiez le réseau et le service SMB dans Nexus.": "The NAS sharing port is unreachable. Check the network and SMB service in Nexus.",
  "Votre lecteur réseau est connecté. Il apparaît dans Ce PC.": "Your network drive is connected. It appears in This PC.",
  "Connexion impossible. Erreur Windows :": "Unable to connect. Windows error:",
  "Windows utilise un autre compte pour ce NAS. Fermez ses fichiers ouverts. Déconnecter uniquement les anciennes connexions de ce NAS et réessayer ?": "Windows is using another account for this NAS. Close its open files. Disconnect only this NAS’s old connections and retry?",
  "Fermez les fichiers et fenêtres ouverts sur ce NAS, puis réessayez.": "Close files and windows open on this NAS, then retry.",
  "Accès refusé. Réparez votre accès dans Nexus et vérifiez les utilisateurs autorisés du partage.": "Access denied. Repair your access in Nexus and check the share’s allowed users.",
  "Serveur introuvable. Vérifiez que Windows est sur le même réseau que le NAS.": "Server not found. Check that Windows is on the same network as the NAS.",
  "Ce partage est introuvable. Téléchargez un nouvel assistant depuis Nexus.": "Share not found. Download a new helper from Nexus.",
  "Cette lettre est déjà utilisée. Choisissez une autre lettre.": "This drive letter is in use. Choose another letter.",
  "Mot de passe incorrect. Utilisez le mot de passe Nexus ou réparez votre accès dans Nexus.": "Incorrect password. Use your Nexus password or repair your access in Nexus.",
  "Identifiants refusés. Utilisez le mot de passe Nexus ou réparez votre accès dans Nexus.": "Credentials rejected. Use your Nexus password or repair your access in Nexus.",
  "Windows conserve un autre compte pour ce NAS. Fermez ses fichiers ouverts, puis réessayez.": "Windows has another account connected to this NAS. Close its open files, then retry.",
  "Windows refuse la connexion SMB. Lancez Vérifier puis Réparer mon accès dans Nexus. Si cela persiste, transmettez ce code au support.": "Windows rejected the SMB connection. Run Check then Repair my access in Nexus. If it persists, send this code to support.",
  "Windows refuse un accès invité. Réparez votre compte SMB dans Nexus.": "Windows rejected guest access. Repair your SMB account in Nexus.",
  "Windows refuse cette méthode d’authentification. Vérifiez les règles de sécurité de ce PC.": "Windows rejected this authentication method. Check this PC’s security policies.",
  "Vérifiez votre accès, puis ouvrez l’assistant sur Windows. Aucune commande à saisir.": "Check your access, then open the helper on Windows. No commands to type.",
  "Vérifier mon accès": "Check my access", "Réparer mon accès": "Repair my access",
  "Rétablit le compte SMB et son accès à ce partage avec votre mot de passe Nexus.": "Restores the SMB account and access to this share using your Nexus password.",
  "Ouvrez le fichier téléchargé : une fenêtre vous demande votre mot de passe Nexus et ajoute le lecteur dans Ce PC.": "Open the downloaded file: a window asks for your Nexus password and adds the drive to This PC.",
  "Connexion manuelle et autres systèmes": "Manual connection and other systems",
  "Service SMB": "SMB service", "Configuration SMB": "SMB configuration", "Accès au partage": "Share access", "Volume connecté": "Volume connected", "Dossier du partage": "Share folder",
  "Votre accès NAS est prêt": "Your NAS access is ready", "Votre accès nécessite une réparation": "Your access needs repair", "À corriger": "Needs attention",
  "Accès SMB rétabli. Ouvrez maintenant l’assistant Windows.": "SMB access restored. Open the Windows helper now.",
  "Aperçu de l’image": "Image preview", "Aperçu indisponible": "Preview unavailable", "Aperçu trop volumineux": "Image too large to preview",
  "La politique Windows bloque l’authentification NTLM utilisée par ce NAS. Contactez l’administrateur de ce PC.": "Windows policy blocks the NTLM authentication used by this NAS. Contact this PC’s administrator.",
  "Disque du partage": "Share disk", "Chargement de l’espace disque…": "Loading disk space…", "Occupation du disque": "Disk usage",
  "disponibles": "available", "Disque plein : espace insuffisant pour déposer des fichiers.": "Disk full: insufficient space to upload files.",
  "Le disque est presque plein.": "The disk is almost full.", "Espace disponible pour vos fichiers.": "Space available for your files.", "Espace disque indisponible": "Disk space unavailable"
};
  const keys = Object.keys(english).sort((a, b) => b.length - a.length);
  const escapePattern = key => [...key].map(char => '.+*?^$()[]{}|\\'.includes(char) ? '\\' + char : char).join('');
  const pattern = '(?<![\\p{L}\\p{N}_])(?:' + keys.map(escapePattern).join('|') + ')(?![\\p{L}\\p{N}_])';
  const matcher = new RegExp(pattern, 'gu');
  const language = () => document.documentElement.lang === 'en' ? 'en' : 'fr';
  const fragment = value => language() === 'en' ? String(value ?? '').replace(matcher, key => english[key]) : String(value ?? '');
  const message = value => {
    const paths = [];
    const protectedText = String(value ?? '').replace(/(['"])(?:\/|[a-z]:\\)[^'"\r\n]*\1/gi, path => { paths.push(path); return `§PATH${paths.length - 1}§`; });
    return fragment(protectedText).replace(/§PATH(\d+)§/g, (_, index) => paths[Number(index)]);
  };
  return { fragment, message, language, locale: () => language() === 'en' ? 'en-GB' : 'fr-FR' };
})();
const pageNames = {
  fr: { dashboard: 'Vue d’ensemble', storage: 'Stockage', shares: 'Partages réseau', users: 'Utilisateurs', files: 'Fichiers', settings: 'Paramètres' },
  en: { dashboard: 'Overview', storage: 'Storage', shares: 'Network shares', users: 'Users', files: 'Files', settings: 'Settings' },
};
const navButtons = document.querySelectorAll('[data-page]');
const pageViews = document.querySelectorAll('.page-view');
const breadcrumbCurrent = document.querySelector('#breadcrumb-current');
const toast = document.querySelector('.toast');
const languageSelect = document.querySelector('#language-select');
const themeToggle = document.querySelector('.theme-toggle');
let language = 'fr', toastTimer;
const shellTranslations = [];
const shellWalker = document.createTreeWalker(document.querySelector('.app-shell'), NodeFilter.SHOW_TEXT);
while (shellWalker.nextNode()) {
  const node = shellWalker.currentNode;
  if (node.textContent.trim()) shellTranslations.push({ node, source: node.textContent });
}
const shellAttributes = [...document.querySelectorAll('[aria-label], [title], [placeholder]')].flatMap(node => ['aria-label', 'title', 'placeholder'].filter(name => node.hasAttribute(name)).map(name => ({ node, name, source: node.getAttribute(name) })));
function readPreference(key) {
  try { return localStorage.getItem(key); } catch { return null; }
}
function savePreference(key, value) {
  try { localStorage.setItem(key, value); } catch {}
}
function showNotice(message) {
  toast.textContent = message; toast.classList.add('visible');
  clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('visible'), 5000);
}
function showPage(page) {
  if (!pageNames.fr[page]) return;
  pageViews.forEach(view => { const active = view.id === `page-${page}`; view.hidden = !active; view.classList.toggle('active', active); });
  navButtons.forEach(button => { const active = button.dataset.page === page; button.classList.toggle('active', active); if (active) button.setAttribute('aria-current', 'page'); else button.removeAttribute('aria-current'); });
  breadcrumbCurrent.textContent = pageNames[language][page];
  history.replaceState(null, '', `#${page}`);
}
function applyTheme(theme, persist = true) {
  const next = theme === 'dark' ? 'dark' : 'light'; document.documentElement.dataset.theme = next;
  const label = next === 'dark' ? (language === 'fr' ? 'Activer le thème clair' : 'Use light theme') : (language === 'fr' ? 'Activer le thème sombre' : 'Use dark theme');
  themeToggle.setAttribute('aria-label', label); themeToggle.title = label;
  themeToggle.querySelector('span').innerHTML = next === 'dark'
    ? '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>'
    : '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 15.6A8.5 8.5 0 0 1 8.4 3.5 8.5 8.5 0 1 0 20.5 15.6Z"/></svg>';
  if (persist) savePreference('maisonnas-theme', next);
}
function applyLanguage(locale) {
  language = locale === 'en' ? 'en' : 'fr'; document.documentElement.lang = language; languageSelect.value = language;
  for (const { node, source } of shellTranslations) {
    if (node.isConnected && !node.parentElement.closest('.profile-copy, .server-card, .page-view, #breadcrumb-current')) node.textContent = NexusI18n.fragment(source);
  }
  for (const { node, name, source } of shellAttributes) if (node.isConnected) node.setAttribute(name, NexusI18n.fragment(source));
  document.title = NexusI18n.fragment('Nexus — Tableau de bord');
  navButtons.forEach(button => { const label = button.querySelector('span:last-child'); if (label) label.textContent = pageNames[language][button.dataset.page]; });
  applyTheme(document.documentElement.dataset.theme, false);
  showPage(document.querySelector('.page-view.active')?.id.replace('page-', '') || 'dashboard');
  savePreference('maisonnas-language', language);
  window.dispatchEvent(new CustomEvent('nexus-languagechange'));
}
navButtons.forEach(button => button.addEventListener('click', () => showPage(button.dataset.page)));
document.querySelector('.brand').addEventListener('click', event => { event.preventDefault(); showPage('dashboard'); });
languageSelect.addEventListener('change', () => applyLanguage(languageSelect.value));
themeToggle.addEventListener('click', () => applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));
applyTheme(readPreference('maisonnas-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'), false);
applyLanguage(readPreference('maisonnas-language') || 'fr');
showPage(pageNames.fr[location.hash.slice(1)] ? location.hash.slice(1) : 'dashboard');
