import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('browser setup, SMB share, file upload/download, folder, removal and account', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  let agentRequests = 0;
  let diskUnavailable = false;
  await page.route('**/api/agent', async route => {
    if (++agentRequests === 1) await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Service Linux temporairement indisponible (test)' }) });
    else if (diskUnavailable) {
      const response = await route.fetch(); const data = await response.json();
      data.disks = data.disks.map(d => ({ ...d, canPartition: false, reason: 'Disque utilisé : une partition est montée' }));
      await route.fulfill({ response, json: data });
    } else await route.continue();
  });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Installer votre NAS' })).toBeVisible();
  await page.getByLabel('Code d’installation').fill('browser-setup-token-1234567890');
  await page.getByLabel('Nom d’utilisateur', { exact: true }).fill('alice');
  await page.getByLabel('Mot de passe', { exact: true }).fill('browser-admin-password');
  await page.getByRole('button', { name: 'Créer mon serveur' }).click();
  await expect(page.getByRole('heading', { name: 'Compte connecté' })).toBeVisible();
  await expect(page.getByRole('alert')).toContainText('Service Linux temporairement indisponible');
  await page.getByRole('button', { name: 'Réessayer' }).click();
  await expect(page.getByRole('heading', { name: 'Votre premier partage' })).toBeVisible();
  await page.route('**/api/system', route => route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ error: 'uv_interface_addresses returned Unknown system error 97' }) }));
  await page.getByRole('button', { name: 'Créer le partage et terminer' }).click();
  const connection = page.getByRole('dialog');
  await expect(connection.getByRole('heading', { name: 'Connecter un lecteur réseau' })).toBeVisible();
  await expect(connection.locator('[data-unc]')).toHaveValue('\\\\127.0.0.1\\documents');
  const helperDownload = page.waitForEvent('download');
  await connection.getByRole('button', { name: 'Télécharger l’assistant Windows' }).click();
  const helper = await helperDownload;
  const helperText = await readFile(await helper.path(), 'utf8');
  expect(helperText).toContain('powershell.exe');
  const helperScript = Buffer.from(helperText.split('::NEXUS_PAYLOAD::\r\n')[1].trim(), 'base64').toString('utf16le');
  expect(helperScript).toContain('WNetAddConnection2');
  const helperConfig = JSON.parse(Buffer.from(/FromBase64String\('([^']+)'\)/.exec(helperScript)[1], 'base64').toString('utf8'));
  expect(helperConfig.path).toBe('\\\\127.0.0.1\\documents');
  expect(helperConfig.account).toBe('nx_alice');
  expect(helperText).not.toContain('browser-admin-password');
  await expect(connection.locator('.connection-checks')).toContainText('Votre accès NAS est prêt');
  await connection.getByLabel('Mot de passe Nexus', { exact: true }).fill('wrong-password');
  await connection.getByRole('button', { name: 'Réparer mon accès', exact: true }).click();
  await expect(connection.getByRole('alert')).toContainText('Mot de passe actuel incorrect');
  await connection.getByLabel('Mot de passe Nexus', { exact: true }).fill('browser-admin-password');
  await connection.getByRole('button', { name: 'Réparer mon accès', exact: true }).click();
  await expect(connection.getByLabel('Mot de passe Nexus', { exact: true })).toHaveValue('');
  await connection.getByRole('button', { name: 'Fermer' }).click();
  await expect(page.getByRole('heading', { name: 'Fichiers', exact: true })).toBeVisible();
  await expect(page.locator('.app-shell')).not.toContainText('Mode démonstration');
  await page.locator('[data-page=settings]').click();
  await expect(page.getByRole('button', { name: 'Rechercher', exact: true })).toBeVisible();
  await page.locator('[data-page=shares]').click();
  await expect(page.getByRole('button', { name: 'Créer un partage', exact: true })).toBeVisible();
  await page.locator('[data-page=files]').click();
  await page.locator('#file-upload').setInputFiles({ name: 'hello.txt', mimeType: 'text/plain', buffer: Buffer.from('Bonjour le NAS') });
  await expect(page.locator('#transfer-progress')).toHaveText('Transfert terminé.');
  await expect(page.locator('#file-rows')).toContainText('hello.txt');
  const download = page.waitForEvent('download'); await page.getByRole('link', { name: 'Télécharger' }).click();
  {
    const file = await download; expect(await readFile(await file.path(), 'utf8')).toBe('Bonjour le NAS');
  }
  await page.getByRole('button', { name: 'Nouveau dossier' }).click();
  await page.getByRole('dialog').getByRole('textbox').fill('photos');
  await page.getByRole('dialog').getByRole('button', { name: 'Continuer' }).click();
  await expect(page.locator('#file-rows')).toContainText('photos');
  await page.locator('tr').filter({ hasText: 'hello.txt' }).getByRole('button', { name: 'Retirer' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirmer' }).click();
  await expect(page.locator('#file-rows')).not.toContainText('hello.txt');
  await page.locator('#file-search').fill('photos');
  await expect(page.locator('#file-rows')).toContainText('photos');
  await page.getByRole('button', { name: 'Ouvrir', exact: true }).click();
  await expect(page.locator('#file-path')).toContainText('photos');
  await expect(page.locator('#file-search')).toHaveValue('');
  await page.locator('#file-upload').setInputFiles({ name: 'Bonjour.txt', mimeType: 'text/plain', buffer: Buffer.from('Inside folder') });
  await expect(page.locator('#file-rows')).toContainText('Bonjour.txt');
  await page.getByRole('button', { name: 'Dossier parent' }).click();
  await expect(page.locator('#file-rows')).toContainText('photos');
  await page.getByRole('button', { name: 'Renommer' }).click();
  await page.getByRole('dialog').getByRole('textbox').fill('albums');
  await page.getByRole('dialog').getByRole('button', { name: 'Continuer' }).click();
  await expect(page.locator('#file-rows')).toContainText('albums');
  await page.getByRole('button', { name: 'albums', exact: true }).click();
  await expect(page.locator('#file-rows')).toContainText('Bonjour.txt');
  await page.locator('#language-select').selectOption('en');
  await expect(page.getByRole('heading', { name: 'Files', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Parent folder' })).toBeVisible();
  await expect(page.locator('#file-rows')).toContainText('Bonjour.txt');
  await expect(page.locator('#file-path')).toContainText('albums');
  await page.getByRole('button', { name: 'New folder' }).click();
  await expect(page.getByRole('dialog')).toContainText('New folder name');
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click();
  for (const [pageName, title] of [['dashboard', 'Hello,'], ['storage', 'Storage'], ['shares', 'Network shares'], ['users', 'Users'], ['settings', 'Settings']]) {
    await page.locator(`[data-page=${pageName}]`).click();
    await expect(page.locator(`#page-${pageName} h1`)).toContainText(title);
  }
  await page.locator('[data-page=shares]').click();
  await page.getByRole('button', { name: 'Connect', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Download Windows helper');
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Create a share', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('Name', { exact: true })).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('Allowed users');
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click();
  await page.locator('[data-page=users]').click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('New password (optional)')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click();
  await page.locator('[data-page=storage]').click();
  await page.getByRole('button', { name: 'Partition…' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Prepare plan' }).click();
  await expect(page.getByRole('dialog')).toContainText('ERASE /dev/testdisk');
  await expect(page.getByRole('dialog')).toContainText('All data will be destroyed.');
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click();
  await page.locator('#language-select').selectOption('fr');
  await page.locator('[data-page=files]').click();
  await page.getByRole('button', { name: 'Dossier parent' }).click();
  await page.getByRole('button', { name: 'Renommer' }).click();
  await page.getByRole('dialog').getByRole('textbox').fill('photos');
  await page.getByRole('dialog').getByRole('button', { name: 'Continuer' }).click();
  await page.locator('#file-search').fill('absent');
  await expect(page.locator('#file-rows')).toContainText('Aucun résultat');
  await page.locator('#file-search').fill('');
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6fZsAAAAASUVORK5CYII=', 'base64');
  await page.locator('#file-upload').setInputFiles([{ name: 'preview.png', mimeType: 'image/png', buffer: png }, { name: 'broken.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('not an image') }]);
  await expect(page.locator('[data-preview="preview.png"]')).toHaveClass(/is-loaded/);
  await expect(page.locator('[data-preview="broken.jpg"] img')).toHaveCount(0);
  await expect(page.locator('[data-preview="broken.jpg"] .ui-icon')).toBeVisible();
  await page.locator('[data-preview="preview.png"]').click();
  await expect(page.getByRole('dialog').locator('.image-viewer img')).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Fermer' }).click();
  await page.unroute('**/api/system');
  // Historical fixture used only for visual/interaction checks; production
  // charts consume the server's real MetricsCollector samples.
  await page.route('**/api/system', async route => {
    const response = await route.fetch(); const data = await response.json();
    const now = Date.now();
    data.history = Array.from({ length: 60 }, (_, i) => ({ time: new Date(now - (59 - i) * 10000).toISOString(), cpu: Math.round(15 + Math.abs(Math.sin(i / 5)) * 25 + Math.abs(Math.sin(i / 2)) * 8), memory: Math.round(34 + Math.sin(i / 9) * 5) }));
    data.cpuPercent = data.history.at(-1).cpu; data.memory = { total: 16 * 1024 ** 3, available: 16 * 1024 ** 3 * (1 - data.history.at(-1).memory / 100) };
    await route.fulfill({ response, json: data });
  });
  await page.locator('[data-page=dashboard]').click();
  await page.getByRole('button', { name: 'Actualiser', exact: true }).click();
  await expect(page.locator('.chart-line').first()).toHaveAttribute('d', /L/);
  await expect(page.locator('#uptime-value')).toContainText('min');
  await expect(page.locator('#uptime-value')).toContainText(' s');
  const firstUptime = await page.locator('#uptime-value').textContent();
  await expect.poll(() => page.locator('#uptime-value').textContent()).not.toBe(firstUptime);
  await page.locator('[data-chart=cpu] .chart-plot').hover();
  await expect(page.locator('[data-chart=cpu] .chart-tooltip')).toBeVisible();
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: test.info().outputPath('dashboard-dark.png'), fullPage: true, animations: 'disabled' });
  await page.evaluate(() => document.documentElement.dataset.theme = 'light');
  await page.screenshot({ path: test.info().outputPath('dashboard-light.png'), fullPage: true, animations: 'disabled' });
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.locator('[data-page=files]').click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: test.info().outputPath('files-dark.png'), fullPage: true, animations: 'disabled' });
  await page.locator('[data-page=users]').click(); await page.getByRole('button', { name: 'Ajouter un utilisateur' }).click();
  const userDialog = page.getByRole('dialog'); await userDialog.getByLabel('Nom', { exact: true }).fill('bob'); await userDialog.getByLabel('Mot de passe', { exact: true }).fill('bob-browser-password'); await userDialog.getByRole('button', { name: 'Créer le compte' }).click();
  await expect(page.locator('#page-users')).toContainText('bob');
  await page.locator('[data-page=storage]').click(); await page.getByRole('button', { name: 'Partitionner…' }).click();
  const partition = page.getByRole('dialog');
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.screenshot({ path: test.info().outputPath('disk-selector.png') });
  await partition.getByRole('button', { name: 'Préparer le plan' }).click();
  await expect(partition).toContainText('EFFACER /dev/testdisk');
  await partition.getByRole('button', { name: 'Fermer' }).click();
  diskUnavailable = true;
  await page.getByRole('button', { name: 'Partitionner…' }).click();
  await expect(page.getByRole('dialog')).toContainText('Aucun disque disponible pour le partitionnement');
  await expect(page.getByRole('dialog').locator('select')).toHaveCount(0);
  await expect(page.getByRole('dialog')).toContainText('une partition est montée');
  await page.screenshot({ path: test.info().outputPath('disk-unavailable.png') });
  await page.getByRole('dialog').getByRole('button', { name: 'Fermer' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-page=files]').click();
  await expect(page.getByRole('heading', { name: 'Fichiers', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy();
  await page.screenshot({ path: test.info().outputPath('files-mobile.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Déconnexion' }).click();
  await expect(page.getByRole('heading', { name: 'Bienvenue sur Nexus' })).toBeVisible();
  await page.locator('.auth-language').selectOption('en');
  await expect(page.getByRole('heading', { name: 'Welcome to Nexus' })).toBeVisible();
  await page.getByLabel('Username', { exact: true }).fill('bob');
  await page.locator('.auth-language').selectOption('fr');
  await expect(page.getByLabel('Nom d’utilisateur', { exact: true })).toHaveValue('bob');
  await page.getByLabel('Nom d’utilisateur', { exact: true }).fill('bob'); await page.getByLabel('Mot de passe', { exact: true }).fill('bob-browser-password');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await expect(page.getByRole('heading', { name: 'Fichiers', exact: true })).toBeVisible();
  await expect(page.locator('#file-path')).toHaveText('Aucun partage autorisé.');
  expect(errors).toEqual([]);
});
